Art.destroy_all
Family.destroy_all
tkd = Art.create(name: "Taekwondo", abbrev: "TKD");
tkd8g = tkd.belts.create(level: "8th Gup", img: "white.png", color: "white", rank: -8);
tkd7g = tkd.belts.create(level: "7th Gup", img: "yellow.png", color: "yellow", rank: -7);
tkd6g = tkd.belts.create(level: "6th Gup", img: "orange.png", color: "orange", rank: -6);
tkd5g = tkd.belts.create(level: "5th Gup", img: "green.png", color: "green", rank: -5);
tkd4g = tkd.belts.create(level: "4th Gup", img: "blue.png", color: "blue", rank: -4);
tkd3g = tkd.belts.create(level: "3rd Gup", img: "purple.png", color: "purple", rank: -3);
tkd2g = tkd.belts.create(level: "2nd Gup", img: "brown.png", color: "brown", rank: -2);
tkd1g = tkd.belts.create(level: "1st Gup", img: "red.png", color: "red", rank: -1);
tkd0g = tkd.belts.create(level: "Deputy Black Belt", img: "deputy.png", color: "red", rank: 0);
tkd1d = tkd.belts.create(level: "1st Dan", img: "black.png", color: "black", rank: 1);
tkd2d = tkd.belts.create(level: "2nd Dan", img: "black.png", color: "black", rank: 2);
tkd3d = tkd.belts.create(level: "3rd Dan", img: "black.png", color: "black", rank: 3);
tkd4d = tkd.belts.create(level: "4th Dan", img: "black.png", color: "black", rank: 4);
tkd5d = tkd.belts.create(level: "5th Dan", img: "black.png", color: "black", rank: 5);
tkd.courses.create(day: "Sunday");
tkd.courses.create(day: "Tuesday");
tkd.courses.create(day: "Wednesday");
tkd.courses.create(day: "Thursday");

hdg = Art.create(name: "Haidong Gumdo", abbrev: "HDG");
hdg8g = hdg.belts.create(level: "8th Gup", img: "white.png", color: "white", rank: -8);
hdg7g = hdg.belts.create(level: "7th Gup", img: "yellow.png", color: "yellow", rank: -7);
hdg6g = hdg.belts.create(level: "6th Gup", img: "orange.png", color: "orange", rank: -6);
hdg5g = hdg.belts.create(level: "5th Gup", img: "green.png", color: "green", rank: -5);
hdg4g = hdg.belts.create(level: "4th Gup", img: "blue.png", color: "blue", rank: -4);
hdg3g = hdg.belts.create(level: "3rd Gup", img: "purple.png", color: "purple", rank: -3);
hdg2g = hdg.belts.create(level: "2nd Gup", img: "brown.png", color: "brown", rank: -2);
hdg1g = hdg.belts.create(level: "1st Gup", img: "red.png", color: "red", rank: -1);
hdg0g = hdg.belts.create(level: "Deputy Black Belt", img: "deputy.png", color: "red", rank: 0);
hdg1d = hdg.belts.create(level: "1st Dan", img: "black.png", color: "black", rank: 1);
hdg2d = hdg.belts.create(level: "2nd Dan", img: "black.png", color: "black", rank: 2);
hdg3d = hdg.belts.create(level: "3rd Dan", img: "black.png", color: "black", rank: 3);
hdg4d = hdg.belts.create(level: "4th Dan", img: "black.png", color: "black", rank: 4);
hdg5d = hdg.belts.create(level: "5th Dan", img: "black.png", color: "black", rank: 5);
hdg.courses.create(day: "Sunday");
hdg.courses.create(day: "Monday");
hdg.courses.create(day: "Tuesday");
hdg.courses.create(day: "Wednesday");
hdg.courses.create(day: "Thursday");
hdg.courses.create(day: "Friday");

hkd = Art.create(name: "Hapkido", abbrev: "HKD");
hkd8g = hkd.belts.create(level: "8th Gup", img: "white.png", color: "white", rank: -8);
hkd7g = hkd.belts.create(level: "7th Gup", img: "yellow.png", color: "yellow", rank: -7);
hkd6g = hkd.belts.create(level: "6th Gup", img: "orange.png", color: "orange", rank: -6);
hkd5g = hkd.belts.create(level: "5th Gup", img: "green.png", color: "green", rank: -5);
hkd4g = hkd.belts.create(level: "4th Gup", img: "blue.png", color: "blue", rank: -4);
hkd3g = hkd.belts.create(level: "3rd Gup", img: "purple.png", color: "purple", rank: -3);
hkd2g = hkd.belts.create(level: "2nd Gup", img: "brown.png", color: "brown", rank: -2);
hkd1g = hkd.belts.create(level: "1st Gup", img: "red.png", color: "red", rank: -1);
hkd0g = hkd.belts.create(level: "Deputy Black Belt", img: "deputy.png", color: "red", rank: 0);
hkd1d = hkd.belts.create(level: "1st Dan", img: "black.png", color: "black", rank: 1);
hkd2d = hkd.belts.create(level: "2nd Dan", img: "black.png", color: "black", rank: 2);
hkd3d = hkd.belts.create(level: "3rd Dan", img: "black.png", color: "black", rank: 3);
hkd4d = hkd.belts.create(level: "4th Dan", img: "black.png", color: "black", rank: 4);
hkd5d = hkd.belts.create(level: "5th Dan", img: "black.png", color: "black", rank: 5);
hkd.courses.create(day: "Monday");
hkd.courses.create(day: "Wednesday");
hkd.courses.create(day: "Friday");

gky = Art.create(name: "Gongkwon Yusul", abbrev: "GKY");
gky8g = gky.belts.create(level: "8th Gup", img: "white.png", color: "white", rank: -8);
gky7g = gky.belts.create(level: "7th Gup", img: "yellow.png", color: "yellow", rank: -7);
gky6g = gky.belts.create(level: "6th Gup", img: "orange.png", color: "orange", rank: -6);
gky5g = gky.belts.create(level: "5th Gup", img: "green.png", color: "green", rank: -5);
gky4g = gky.belts.create(level: "4th Gup", img: "blue.png", color: "blue", rank: -4);
gky3g = gky.belts.create(level: "3rd Gup", img: "purple.png", color: "purple", rank: -3);
gky2g = gky.belts.create(level: "2nd Gup", img: "brown.png", color: "brown", rank: -2);
gky1g = gky.belts.create(level: "1st Gup", img: "red.png", color: "red", rank: -1);
gky0g = gky.belts.create(level: "Deputy Black Belt", img: "deputy.png", color: "red", rank: 0);
gky1d = gky.belts.create(level: "1st Dan", img: "black.png", color: "black", rank: 1);
gky2d = gky.belts.create(level: "2nd Dan", img: "black.png", color: "black", rank: 2);
gky3d = gky.belts.create(level: "3rd Dan", img: "black.png", color: "black", rank: 3);
gky4d = gky.belts.create(level: "4th Dan", img: "black.png", color: "black", rank: 4);
gky5d = gky.belts.create(level: "5th Dan", img: "black.png", color: "black", rank: 5);
gky.courses.create(day: "Sunday");
gky.courses.create(day: "Monday");
gky.courses.create(day: "Wednesday");
gky.courses.create(day: "Friday");

f = Family.create(name: "Banasiewicz");
p = f.people.create(first_name: "Carolina", last_name: "Banasiewicz", dob: Date.new(1970, 8, 22));
Rank.create(belt: tkd4d, person: p);
Rank.create(belt: hdg4d, person: p);
p = f.people.create(first_name: "Monroe", last_name: "Banasiewicz", dob: Date.new(2007, 1, 5));
Rank.create(belt: tkd1d, person: p);
Rank.create(belt: hdg1d, person: p);
p = f.people.create(first_name: "Flynn", last_name: "Banasiewicz", dob: Date.new(2009, 10, 15));
Rank.create(belt: tkd1g, person: p);
Rank.create(belt: hdg6g, person: p);
f = Family.create(name: "Marudas");
p = f.people.create(first_name: "Colette", last_name: "Marudas", dob: Date.new(2005, 2, 21));
Rank.create(belt: tkd4d, person: p);
p = f.people.create(first_name: "Gunnar", last_name: "Marudas", dob: Date.new(2007, 1, 6));
Rank.create(belt: tkd1g, person: p);
p = f.people.create(first_name: "Palmer", last_name: "Marudas", dob: Date.new(2009, 5, 8));
Rank.create(belt: tkd3g, person: p);
p = f.people.create(first_name: "Moses", last_name: "Marudas", dob: Date.new(2012, 7, 11));
Rank.create(belt: tkd4d, person: p);
Rank.create(belt: hdg4d, person: p);
Rank.create(belt: gky2d, person: p);
f = Family.create(name: "Tahhan");
p = f.people.create(first_name: "Dennis", last_name: "Tahhan", dob: Date.new(1985, 10, 12));
Rank.create(belt: tkd2d, person: p);
Rank.create(belt: hdg4d, person: p);
f = Family.create(name: "Protich/Vozenilek");
p = f.people.create(first_name: "Justice", last_name: "Vozenilek", dob: Date.new(1982, 3, 22));
Rank.create(belt: tkd2d, person: p);
Rank.create(belt: hdg2d, person: p);
p = f.people.create(first_name: "Mallory", last_name: "Protich", dob: Date.new(1984, 5, 18));
Rank.create(belt: tkd2d, person: p);
Rank.create(belt: hdg5g, person: p);
p = f.people.create(first_name: "Quincy", last_name: "Protich", dob: Date.new(2007, 6, 17));
Rank.create(belt: tkd1g, person: p);
Rank.create(belt: hdg5g, person: p);
p = f.people.create(first_name: "Tate", last_name: "Protich", dob: Date.new(2007, 8, 12));
Rank.create(belt: tkd2d, person: p);
Rank.create(belt: hdg4g, person: p);
